default:
    suites:
        cli_installer:
            contexts:
                - App\Tests\Behat\Context\Hook\DoctrineORMContext

                - App\Tests\Behat\Context\UI\Cli\CommandContext
                - App\Tests\Behat\Context\UI\Cli\InstallerContext
            filters:
                tags: "@cli&&@installer"
