default:
    suites:
        ui_managing_authors:
            contexts:
                - App\Tests\Behat\Context\Hook\DoctrineORMContext
                - App\Tests\Behat\Context\Setup\AdminSecurityContext
                - App\Tests\Behat\Context\Setup\AuthorContext

                - App\Tests\Behat\Context\Transform\SharedStorageContext

                - App\Tests\Behat\Context\UI\Backend\Blog\ManagingAuthorsContext
                - App\Tests\Behat\Context\UI\Backend\NotificationContext
            filters:
                tags: "@backend&&@blog&&@authors"
